### ISSUE TITLE
Error occurs when a backlink iterable is empty

### ISSUE THREAD

**Issue by Taco55** [realm/realm-dart#1106]
### What happened?

For example:

```
@Backlink(#items)
late Iterable<$ExampleList> exampleLists;
```

When an item has no relationship with `ExampleList`, it seems not possible to access `exampleLists`.

`print(item.exampleLists.isEmpty);
`

results in:

```
Exception has occurred.
_CastError (type 'Null' is not a subtype of type 'RealmResults<ExampleList>' in type cast)
```

### Repro steps

See above

### Version

2.19.0-444.3.beta / 3.7.0-1.3.pre

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

0.9.0+rc

**Comment by nielsenko** [comment]
Hi @Taco55 

You have not added the `item` object to the realm yet. Backlinks only work on managed object, ie. objects that are persisted in the realm. The error message could be better though.

**Comment by nielsenko** [comment]
I see two options here. 

1. Either we throw an error when trying to access a synthetic property such as a backlink on an unmanaged object. 
2. Or we ensure the returned `Iterable<T>` is empty, when accessing a backlink property on an unmanaged object. 

I/we prefer option 2), but there is complication in that the returned value is not really of type `Iterable<T>`, but the _covariant_ `RealmResults<T>`. This has many advantages when working with backlinks on managed objects. Fx. you don't to cast to get to the `changes` stream, but it does complicate this option a bit.

**Comment by Taco55** [comment]
One of these options would be highly desirable. I agree that the second options would be best when it is not possible to backlink unmanaged object.  

For my project is it required to work with the unmanaged objects. I use it in several form, where all data can be canceled and realm listeners should not be triggered before saving. 

A somewhat related question. Is there a better option to detach managed objects, instead of iterating through all properties and copying them? Especially with release 0.9rc this is quite cumbersome since all the property names from the RealmObjectBase mixin are now based on the model names, while SchemaObject only provides the mapped names.

**Comment by nielsenko** [comment]
@Taco55 Unmanaged realm objects are more or less plain Dart objects, they don't get their magic until added to a realm. In particular backlink properties, support for changes, the ability to freeze etc. are reserved for managed objects. We don't capture the distinction between managed and unmanaged objects in the type system, so this is why this is a runtime error.
 
Regarding working with unmanaged objects - I suggest keeping the period as short as possible. You could consider not assembling the realm object until the user press save, or opening a transaction upon entry on the form page, creating the object immediately, but only commit the transaction when the user press save, and rollback the transaction on cancel. Note that the `changes` streams only pumps between transactions.

Instead of copying out the properties, why not just `freeze` the object? This pins the object at the current version. You can no longer change it, it will not raise notifications, but you can still traverse the object graph (as it looked at that version), including backlinks. 

That said, I guess you are on the lookout for something somewhat related to what is discussed [here](https://github.com/realm/realm-dart/issues/1076#issuecomment-1359532229) and here #1077.

**Comment by Taco55** [comment]
Many thanks for your answer, since I also use forms to edit already managed objects I need a way to change the objects, so freezing objects seems not a solution. I don't see why starting a transaction when opening a form would be better than (temporary) working with unmanaged objects (e.g. a new entry in a form is also based on an unmanaged object before it is saved).  Besides that I try to separate all business logic and storage from the ui in combination with BloC for state management, so all transactions are performed elsewhere. 

For me it would be most helpful to have an easy option to make a deep copy of an object, like it is has been proposed for Swift [https://github.com/realm/realm-swift/issues/3381](url). With Flutter I was not able to do it in the exact same way...

Anyway, thanks for your help and for pointing me to the other discussions.

**Comment by nielsenko** [comment]
It is fine to use temporary(/short lived) unmanaged objects. That was what I tried to suggest. Just don't expect unmanaged realm objects to support backlinks, etc.

Doing a deep-copy could be exceptionally expensive, as we would need to traverse all objects reachable from the current, and copy out all their properties. This defeats one of the prime features of realm objects, ie. that you don't pay for stuff you don't access. With Realm everything is fetched lazy, down to the individual fields.

I'm not sure why you find that this makes fitting realm with the BLoC pattern a challenge, I would need to see your code to comment on that.

**Comment by Taco55** [comment]
@Taco55 Sorry for my late response and thanks for your helpful thoughts.

That seems like a good point to me. Are you also saying that when all properties are copied, they will be (unnecessarily) synced and making traffic? Or is that only when these have been changed like in a managed object? Anyway, I am convinced to work with opening a transaction instead of detaching a Realm object.
