### ISSUE TITLE
Named pipes are breaking flutter in MacOS

### ISSUE THREAD

**Issue by maBarabas** [realm/realm-dart#1166]
### What happened?

After installing realm and running some unit tests, `flutter run` and `flutter build` stopped working.

This is caused by the named pipes that are created by the test implementation of realm. Reported in this flutter issue: https://github.com/flutter/flutter/issues/108805

This could be fixed by changing the default directory for files created by realm to `/tmp`.

### Repro steps

1. Create a project with realm used in a widget test
2. Run the widget tests
3. Observe that some named pipes are left behind by realm
    * default.realm.note
    * default.realm.management/access_control.new_commit.cv
    * default.realm.management/access_control.pick_writer.cv
4. Run `flutter run --verbose`
5. Observe that it is stuck at `xattr -r -d com.apple.FinderInfo /path/to/project`

### Version

Flutter 3.7.1 • channel stable • https://github.com/flutter/flutter.git Framework • revision 7048ed95a5 (2 weeks ago) • 2023-02-01 09:07:31 -0800 Engine • revision 800594f1f4 Tools • Dart 2.19.1 • DevTools 2.20.1

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

MacOS 13.1 (22C65)

### Code snippets

our realm configuration:

```
    final config =
        Configuration.local([DatabaseSystem.schema, DatabaseDevice.schema]);
    _realmDatabase = Realm(config);
```

**Comment by blagoev** [comment]
Hi, 
Is it the second time you run the tests that it fails. If so can you try calling this API at the end of your tests
`Realm.shutdown ()`. This will make sure Realm is torndown completly before the next run.

Cheers

**Comment by maBarabas** [comment]
The tests keep working, the problem is `flutter run` does not work any more because of the pipes.

I will work around for now by deleting the default database in teardown, but making a mistake and not tearing down will cause most of the flutter commands to stop working. It took me a long time find the root cause of this. I think realm should be nice here and put the pipes somewhere else to avoid breaking flutter.

**Comment by blagoev** [comment]
@maBarabas Thanks for reporting and for the PR. We will try to investigate if we can provide a fix on that (similar to yours) or we will at least document a workaround for it. 

cheers

**Comment by desistefanova** [comment]
Hi @maBarabas ,
We discussed the issue with the team and as we understand from the [PR ](https://github.com/realm/realm-dart/pull/1167)that you have opened, it will work for you if Flutter and Dart tests can store their realm files to a temporary directory.

The Realm files location and names could be configured. You can find a sample in this document about[ setting `Configuration.defaultRealmPath`](https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/configure-and-open/#customize-default-configuration)

Before running the tests you can set `Configuration.defaultRealmPath` to a custom path or a temp directory on [setUp](https://api.flutter.dev/flutter/flutter_test/setUp.html) or [setUpAll](https://api.flutter.dev/flutter/flutter_test/setUpAll.html) functions. Here is the example:
```dart
final customDefaultRealmPath = path.join(
    (await Directory.systemTemp.createTemp()).path,
    Configuration.defaultRealmName);
Configuration.defaultRealmPath = customDefaultRealmPath;
```
[Configuration.defaultRealmPath ](https://pub.dev/documentation/realm/latest/realm/Configuration/defaultRealmPath.html)requires the full path.

You can also find examples about [setting up Flutter tests with Realm](https://www.mongodb.com/docs/realm/sdk/flutter/test-and-debug/#test-using-a-default-realm.). The example demonstrates changing only the name of the realm file, but in a similar way you can change the path and the name using `Configuration.defaultRealmPath` instead of `Configuration.defaultRealmName`.
If you scroll down you will find samples on how to delete your files at the end of the tests, which I suppose you have already done.
Please, let us know whether this is a solution for you!
