### ISSUE TITLE
How to embed dart library classes

### ISSUE THREAD

**Issue by vandir** [realm/realm-dart#1170]
Is there a way to embed library classes such as Duration, Rectangle, etc?

I want to create a schema like this:

```dart
import 'dart:math';
import 'package:realm_dart/realm.dart';

part 'all_models.g.dart';

@RealmModel()
class _Car {
  late String make;

  late String model;

  late Rectangle<int> size;
}
```

**Comment by desistefanova** [comment]
Hi @vandir!
All the types that Realm supports are listed here in the [documentation](https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/model-data/data-types/).
But you can store the points of the rectangle, or the milliseconds of the durations using `double`, `int` types, so that you can easily restore them to a new Rectangle or Duration after reading the data from the Realm.
You can use embedded objects `ObjectType.embeddedObject` so that when you read the `Car` object, the points of the rectangle will be also read embedded. You won't need to care about the references to the points.
Here is one example:


```dart
import 'dart:math';
import 'package:realm/realm.dart';

part 'all_models.g.dart';

@RealmModel(ObjectType.embeddedObject)
class _Points {
  final int left = 0;
  final int top = 0;
  final int width = 0;
  final int height = 0;
}

@RealmModel()
class _Car {
  late String make;

  late String model;

  late _Points? points;

  Rectangle<int> get rectangle => Rectangle<int>(
        points?.left ?? 0,
        points?.top ?? 0,
        points?.width ?? 0,
        points?.height ?? 0,
      );

 set rectangle(Rectangle<int> value) =>
        points = Points(left: value.left,
         top:value.top,
         width:  value.width,
         height:
         value.height,
         );
}
```

**Comment by vandir** [comment]
Hi @desistefanova, many thanks for your alternative solution! Please consider adding in the future an out of the box support for Duration class as it is very common and stritcly realted with DateTime (which you chose to support). :-)
