### ISSUE TITLE
Deleted user can still make update from another device

### ISSUE THREAD

**Issue by geosebas** [realm/realm-dart#1177]
### What happened?

Hello ! 

Just got this case after trying to implement user deletion function. 

With one device connected, everything work well.
I cannot find any way in the docs to have the update on all device that the user has been deleted.
So I cannot 'logout' the user from all devices on deletion. 

Moreover, realm allow a deleted user to make update on synced database. 

IMHO, the sdk should allow to register to a stream to get user updates or something like that. 

We got the same problem with the 'Revoke all sessions' button from Atlas Ui, the user with revoked session can still continue to make updates.

### Repro steps

Log in with the same user on at least 2 devices. 

Delete user following the doc steps : 
```
final currentUser = app.currentUser!;
await app.deleteUser(currentUser);
```

### Version

Flutter 3.7.3

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

1.0.1

**Comment by geosebas** [comment]
I'm not sure if I correctly understood the doc, but it said :
> This deletes the account from the App on the server in addition to clearing local data.

'Local data' meaning for me the user's realm.

But when I try to log in again just after, I got this error  
`Received: ERROR "User mismatch for client file identifier (IDENT)"`
So the realm file hasn't been deleted. 

Either it's another bug or you should fix the doc I think :)

**Comment by geosebas** [comment]
Anyone ?

**Comment by geosebas** [comment]
Hi @nirinchev, sorry to tag you here, but wanted to know if anyone saw this bug ?

**Comment by nirinchev** [comment]
Hey, sorry, this must have slipped - I'll ping the team to try and take a look.

**Comment by nielsenko** [comment]
@geosebas Sorry that we dropped the ball on this.

We have actually been discussing this with server guys, and frankly the answer is not what you (or we for that matter) hoped for.

When a user is deleted the tokens already granted does not expire immediately, and the session established with these (on other devices) can run for quite a while - as you have discovered.

This is inherent in the current design, and (as I understand) not something that will likely change soon. To achieve the behaviour you request you have to roll-your-own solution.

You could have a `UserProfile` class along the lines of:
```dart
@RealmModel()
class _UserProfile {
  @PrimaryKey()
  @MapTo('_id')
  late String id; // matches user.id

  @MapTo('owner_id')
  late String ownerId; // matches user.id

  late String? name; // just an example of some public user data
}
```
Whenever a `user` authenticates you find or create a matching `UserProfile` with primary key matching `user.id` (and matching `owner_id`)

You can use the profile to share public user data between users, etc. Make sure to setup your security rules for the `UserProfile` so that only the owner can write/delete.

In your app listen for changes to the logged in user, in particular listen for the `UserProfile` object to die. When that happens call `App.deleteUser`

When the user on one device decides to delete his user, or some admin process does. Delete the associated `UserProfile` (which is only writable by the owning user, or an admin) which will then trigger the deletion of the `User` on all devices.

Would an approach like that work for you?

**Comment by dotjon0** [comment]
@nielsenko another approach would be to use https://www.mongodb.com/docs/atlas/app-services/authentication/custom-jwt/#firebase-jwt-authentication or is this an issue with 'sessions' with Realm User auth regardless?

**Comment by nielsenko** [comment]
I don't think changing the provider will do you much good. It may change the livetime of the tokens, since these are set by the provider, but I believe firebase tokens are valid for 30 minutes.

As to revoking sessions using the atlas end-point - I may be mistaken, but I believe it will just revoke the refresh token, not the already granted user_id and access tokens, so I expect you to have the same issue.

Also, even if the refresh tokens are revoked and the user_id/access tokens eventually time out, I don't think any established web socket connections are torn down, until an actual reconnect is attempted.

However, if you do as I described, ie.
```dart
  await for (final change in userProfile.changes) {
    if (change.isDeleted) {
      await user.app.deleteUser(user);
      exit(64);
    }
  }
```
some strategic place, then it will work immediately. I just tested on a sample I'm working on.

**Comment by geosebas** [comment]
Hi @nielsenko, thanks for your answer.

I need to say that I didn't expect this answer. I was thinking that I did something wrong somewhere ^^ 
But what I don't understand is why give the user an api (and button in atlas) to revoke user's session if nothing is happening ?

> When the user on one device decides to delete his user, or some admin process does. Delete the associated UserProfile (which is only writable by the owning user, or an admin) which will then trigger the deletion of the User on all devices.

I will do this, should not be to hard to implement since I already have an `UserProfile` like collection. But that means I will call `await user.app.deleteUser(user);` multiple time. That's not a problem I hope ? 

Thanks a lot for your help !

**Comment by nielsenko** [comment]
Something is happening, in that once the already granted tokens timeout, the user cannot re-connect anymore.. it just happens on a much longer time horizon than you/we would like. Also remember that most Atlas App Services don't use long standing web sockets, like Device Sync (or GraphQL)

To be honest you where not the only one to be surprised by this, but thinking about from the perspective of OpenID Connect and OAuth2 it kind of makes sense.

That said we could definitely have a better experience, but it will require some changes to `realm-core` I believe.

Also, I find it useful to have a`UserProfile` class for sharing public user data anyway, and the amount of code you need to roll-your-own is quite small.

**Comment by geosebas** [comment]
> Something is happening, in that once the already granted tokens timeout, the user cannot re-connect anymore.. it just happens on a much longer time horizon than you/we would like. Also remember that most Atlas App Services don't use long standing web sockets, like Device Sync (or GraphQL) does.

You're right, I didn't think about this. 
But we're okay that once the token has been revoked, you cannot do any other request with it ?

**Comment by geosebas** [comment]
Just finished my implementation  ! Everything is working well but you cannot call multiple time `deleteUser`, that will throw an exception. 

Here is my own code that seems to work well and should be deleting all user data on device. 

Method called by user to delete his account : 
```
  Future<void> deleteUser() async {
    final realmService = locator<RealmService>();
    await _playerSubscription?.cancel();
    final realm = await realmService.realm;
    realm.write(() {
      currentPlayer!.deleted = true;
      currentPlayer!.userId = null;
    });
    currentPlayer = null;
    await realm.syncSession.waitForUpload();
    await realmService.closeAndTryDeleteRealm();
    realmService.app.deleteUser(currentUser!);
  }
```

On login and/or when the user open the app, subscribe to the stream : 
` _playerSubscription = currentPlayer!.changes.listen(_listenToDeletedPlayerChanges);`

Listener : 
```
  Future<void> _listenToDeletedPlayerChanges(RealmObjectChanges<Player> changes) async {
    if (changes.isDeleted || changes.object.deleted) {
      final realmService = locator<RealmService>();
      await _playerSubscription?.cancel();
      final realm = await realmService.realm;
      currentPlayer = null;
      await realm.syncSession.waitForUpload();
      await realmService.closeAndTryDeleteRealm();
      if (realmService.app.currentUser != null) {
        await realmService.app.removeUser(realmService.app.currentUser!);
      }
    }
  }
```

We can close this issue if it's okay for you :) 

Thanks a lot again !

**Comment by nielsenko** [comment]
A small observation..
```dart
...
await realmService.app.deleteUser(currentUser!); // you are missing an await
...
```
