### ISSUE TITLE
Property type List<String> not supported

### ISSUE THREAD

**Issue by ahmdaeyz** [realm/realm-dart#1350]
### What happened?

I keep getting this exception when I use the `IN` operator

RealmException: Property type List<String> not supported

### Repro steps

In my case symbols is a list (not growable)
<img width="893" alt="image" src="https://github.com/realm/realm-dart/assets/36048466/6315cc8d-fb3d-4e09-a8bd-532a11dea5ee">

I actually tried using the RealmList type but I get a similar error.
Am I missing something? 

### Version

1.3.0

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### What type of application is this?

Flutter Application

### Client OS and version

iPhone 13, iOS 16.5.1

**Comment by ahmdaeyz** [comment]
I think https://github.com/realm/realm-dart/pull/1346 is related to this issue.

**Comment by desistefanova** [comment]
Hi @ahmdaeyz!
Yes you are right. We have a PR #1346 that fixes this issue but it is still not released.
By this time you can make it work if you build the query as a string instead of passing the list as a query parameter.
We have similar #1084 and you can find a working sample there. 
I'm closing this issue as a duplicate.
Thanks for the report!
