### ISSUE TITLE
Force reconnect to MongoDB (syncSession.pause() and syncSession.resume())

### ISSUE THREAD

**Issue by raivac** [realm/realm-dart#1385]
### What happened?

I have a question about how to force the reconnection with mongodb when I lose the connection to the network and recover it later. Until version 1.3.0 it used syncSession.pause() and syncSession.resume(), but from what I've been observing these days this no longer works (I don't know if on purpose or it's a bug in the latest version) the question that I have is if there is any other way to force the reconnection with mongodb and not have to wait the 5 minutes until it tries again on its own

### Repro steps

```dart
  forceManualReconnection() {
    try {
      client!.syncSession.pause();
      client!.syncSession.resume();
    } catch (e) {
      print(e);
    }
  }
  ```
  

### Version

1.4.0

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

Android 10

**Comment by nielsenko** [comment]
@raivac I fear this might be a consequence of commit 4ad1fe589 which enabled session multiplexing.
This change did not make it into the CHANGELOG.md, because it was considered internal.

I'm afraid the only workaround I can suggest is to stay on 1.3.0 (for now), if this is important to you, since we do not allow you to customise the session multiplexing behaviour in the Flutter and Dart SDK.

I will return when I know more.

**Comment by nielsenko** [comment]
@raivac For your particular use-case (if I read it correctly) you should just call `app.reconnect()` instead, when a NIC connects to some network.

However, we do have an [issue](https://github.com/realm/realm-js/issues/6058#issuecomment-1686111388) regarding refresh of user data that some people used `suspend+resume` to work around, and this work-around doesn't work after session multiplexing was introduced.

But that is not your concern. Sorry for the confusion.

**Comment by raivac** [comment]
Thank you very much for the solution :)
