### ISSUE TITLE
Convert anonymous user to 

### ISSUE THREAD

**Issue by frankmungnodev** [realm/realm-dart#1417]
### Problem

Firstly I login user anonymously so user can save their data. If user want to sign-in with email and password, I check if the user already exist and If user not exists, I link the credentials with current user, but if user exists I just login and then I can no longer query user related data, If I want to query user related data again, I need to restart my app.

### Solution

How to do it without restarting my app, because it make user experience very bad. In my case I use custom function login to check user with mobile number.

### How important is this improvement for you?

Dealbreaker

### Feature would mainly be used with

Atlas App Services: Auth or Functions etc

**Comment by dotjon0** [comment]
Do you have a minimum example of a working app to demonstrate this ?

**Comment by nirinchev** [comment]
So the issue is that Atlas App Services offers the option to link credentials to a user, but there's no possibility to merge two users into one. In the case of an anonymous user who then authenticates with username/password of an already existing user, you'll probably need to manually copy the anonymous user data to the new authenticated user data.

I'm not sure how your app is designed and why it needs a restart, but that should be avoidable. It's perfectly acceptable to have multiple users authenticated at the same time, so you should be able to swap out the Realm owned by the anonymous user with the one owned by the email/password user.

**Comment by frankmungnodev** [comment]
Well I resolve the issue by re-open realm after I login, then unregister Realm instance from `getIt` and register again. 

And instead of using realm like this
 ```
final realm = getIt<Realm>()

realm.all<User>()
```

I use it like this
```
getIt<Realm>().all<User>()
```
