### ISSUE TITLE
Realm RQL & FTS Synonyms

### ISSUE THREAD

**Issue by dotjon0** [realm/realm-dart#1421]
### Problem

Realm RQL and FTS do not support Synonyms.

### Solution

Realm RQL and FTS to support Synonyms.

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Atlas Device Sync

**Comment by nirinchev** [comment]
We don't have immediate plans to add synonym support to FTS search in the local database. The recommendation for now would be to use Atlas Search for use cases where a more feature-rich search experience is required. While this is already available in other SDKs, for Flutter, it depends on https://github.com/realm/realm-dart/issues/784 to be able to run aggregations.

**Comment by dotjon0** [comment]
@nirinchev it seems odd other Realm SDKs have this feature, yet its not planned for the Flutter/Dart Realm SDK? The whole point of Realm with Device Sync is for an 'offline first' approach, so this is yet another feature around search that does not support this approach...

**Comment by nirinchev** [comment]
No SDK supports synonyms and this feature is not planned for other SDKs either. I was referring to the ability to run remote MongoDB queries and aggregations, which is available on other SDKs and is definitely planned for Flutter, though we don't have a timeline for this yet.

For more context around the local-only full-text search API - this was always intended to be a fairly minimalistic as there's a significant tradeoff there with the library size and the complexity of the codebase as we add more and more functionality (Atlas Search and Lucene are massive compared to the size of the Realm SDK). Considering this is not a mainstream feature, we don't think it's justified to impose the negatives to everyone using the SDK.

If having offline FTS available is critical for the UX in your app, what you can do is filter things as much as possible using the Realm API, then use a 3rd party library, like [Mobile Lucene](https://github.com/lukhnos/mobilelucene) to further filter the dataset in memory. Since Realm is an embedded database, filtering data outside the database is not as expensive as developers typically fear it is.

**Comment by dotjon0** [comment]
Thanks @nirinchev - https://github.com/lukhnos/mobilelucene looks a bit early and experimental. What about synonyms in RQL, is this a consideration? Appreciate your FTS feedback.

We could build our own synonyms logic in Flutter/Dart and store all the synonyms locally in a Realm model (via Device sync) - although this could dramatically increase the query complexities/size via RQL and FTS in Realm Flutter/Dart SDK, so would this cause any performance issues? Are there any hard limits or performance limits we should be aware of?

**Comment by nirinchev** [comment]
Right now synonym support is not on our short-term roadmap. I agree it's a useful feature and we do eventually want to support it, but we haven't received enough requests for it to justify prioritizing it higher (you're the first person to request it so far).

Regarding synonym search, one option would be to tokenize the string stored in the database and extract synonyms for each token, but that would typically be memory-inefficient. Instead, you could instead tokenize the search string and generate multiple queries using the synonyms. For example, if you tokenize the sentence "The company executed multiple transactions in FY 2024" and store the tokens in a list in your model, you'd end up with something like `[ "company", "execute", "multiple", transaction", "FY", "2024"  ]`. Then if a user searches for `"sale"`, you can lookup the synonyms for `sale` and generate an RQL query against the tokens, that would look something like: 

```dart
// This will result in something like "'sale','transaction','deal','bargain'".
final synonyms = Dictionary.lookup("sale").map((e) => "'$e'").join(",");
final matches = realm.query<MyModel>("ANY tokens in { $synonyms }");
```

This will match the above sentence, because there'll be at least one token that matches one of the synonyms supplied. This will be more computationally expensive than if you stored all tokens along with their synonyms, but will be more memory efficient.

In terms of performance, our recommendation would be to measure things for your particular use case with data sizes and query complexities that are representative for your average use case. There are no hard limits imposed by Realm.

**Comment by dotjon0** [comment]
Thanks @nirinchev really appreciate your help - this is the approach we had in mind i.e. a Ream Model for 'synonyms' (that we sync with Device Sync and includes a huge number of synonyms for example from wordnet). We can then RQL query this 'synonyms' Realm Model via a token list (as in your example to get synonyms for each token list item), which we can inject (the relevant synonyms) into the original search string. Is this what you were suggesting as the best route from a performance, experience, etc point in view?

**Comment by nirinchev** [comment]
It really depends on how you want to build your app - e.g. if you want to dynamically download the dictionaries based on the user locale, the approach above would work fine. If you instead wanted to just bundle every single language for each user, you could build a local Realm file with this data and bundle it in your application to make sure it's available immediately on install. Since most people will try to use wifi to download new apps, this will likely save them transfer fees.

**Comment by dotjon0** [comment]
perfect, thank you so much for all your insights and advice on this @nirinchev, appreciated!
