### ISSUE TITLE
MongoDB Atlas Search support

### ISSUE THREAD

**Issue by dotjon0** [realm/realm-dart#1423]
### Problem

It would be useful if MongoDB Atlas Search could be queried directly via the Realm Flutter/Dart SDK. This will reduce the development time needed i.e. there will be no need to spin up a Search API service that utilises MongoDB Atlas Search under the covers.

### Solution

See above

### Alternatives

See above

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Atlas Device Sync

**Comment by nirinchev** [comment]
This is already captured (although admittedly not in obvious way) by https://github.com/realm/realm-dart/issues/784. Since Altas Search is just a stage in an aggregation pipeline, once we have support for aggregations, that will enable `$search` along with all the other aggregation stages.

It is our plan to add support for aggregations, along with all the other remote MongoDB operators but we don't have exact timeline yet.

I'm going to close this issue as a duplicate but feel free to continue the discussion in https://github.com/realm/realm-dart/issues/784 if you have further questions/comments.

**Comment by dotjon0** [comment]
Thank you @nirinchev, thats very good news to provide a better 'online' search experience without building out a search sevice. Many thanks again.
