### ISSUE TITLE
Adding a Property Causing RealmException

### ISSUE THREAD

**Issue by maxmiranda** [realm/realm-dart#1501]
### What happened?

In the documentation for Realm Flutter, in no uncertain terms, it says: “Realm can automatically migrate added and deleted properties. You must update the schema version when you make these changes.” ([https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/model-data/update-realm-object-schema/#add-a-property 1](https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/model-data/update-realm-object-schema/#add-a-property)).

I performed the following:

Added the testProp field below:
```
@RealmModel()
class _SavedItem {
  @PrimaryKey()
  late String key;
  @Indexed()
  late String type;
  late int itemId;
  int trackingId = 0;
  late String title;
  late String? image;
  late int? duration;
  late String? subtitle;
  late String? data;
  List<int> topicIds = [];
  List<String> topicNames = [];
  late String? testProp;
}
```
Ran `dart run realm generate`
Incremented the `realmSchemaVersion` in the code below
```
realmSchemaVersion = 5 // was 4 before
final realm = Realm(Configuration.local( [SavedItem.schema], schemaVersion: realmSchemaVersion, migrationCallback: (migration, oldSchemaVersion) {}, ));
```

Yet when I reopened my app, I was greeted with a RealmException, as shown below:
![image](https://github.com/realm/realm-dart/assets/24932260/5f78a0b7-dbed-4d1c-88f7-e216b1be8d02)

Is there anywhere I can check to see if I’m doing anything wrong? If I’m not doing anything wrong, why is the automatic migration which the documentation described not happening??

### Repro steps

1. Create a realm model
2. Run all necessary commands to get the app up and running
3. Add a field to that model 
4. Increment realm schema version + re-generate the code for the realm model + observe realm exception

### Version

Dart: 3.2.5, Flutter: 3.16.8

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

on my Macbook Pro running Sonoma 14.2.1

**Comment by nirinchev** [comment]
I've created a simple console app in dart to try and reproduce this behavior and haven't been able to. Please find the repro project attached and check if it works as expected on your machine as it does on mine.

[migration-repro.zip](https://github.com/realm/realm-dart/files/14104127/migration-repro.zip)

To run the sample the first time, you can do:

```sh
dart pub get
dart run realm_dart install
dart run
```

You should see a `default.realm` get created in the same folder and the console log should look something like:

```log
Opening Realm at path /xxx/default.realm with schema version 4
Opened successfully
```

Then, to simulate a migration, do the following:
1. Uncomment `testProp` in `model.dart`
2. Run `dart run realm_dart generate`
3. Update `realmSchemaVersion` in `migration_repro.dart`
4. Run `dart run`

The log should now look something like:

```log
Opening Realm at path /xxx/default.realm with schema version 5
Migration invoked with old schema version: 4
Opened successfully
```

All of this is behaving as we'd expect it to, so can you compare the flow in my repro project with the flow in your app and let us know what's different so that we can reproduce the behavior you're seeing.
