### ISSUE TITLE
Custom Data Serialization  (improvement)

### ISSUE THREAD

**Issue by davidAg9** [realm/realm-dart#1609]
### Problem

I want to inherit from realm user in order for easy serialisation with the custom data.see below
![image](https://github.com/realm/realm-dart/assets/56321266/ca9a268e-7c9e-40fa-bcba-8157014f0aa3)

currently the the above code doesnt work due to the implementation of private constructor.

### Alternatives

I can use class  composition but that will just not give me the built in type matching and inheritance functionality.

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Atlas App Services: Auth or Functions etc

**Comment by nirinchev** [comment]
Instead of extending the class, you could add an extension method:

```dart
extension CPUser on User {
  CPStaffDetails get staffDetails => CPStaffDetails.fromJson(customData);
}
```

Note that the `customData` returned by `User` is a map representing the json structure of the custom data (as returned by calling `jsonDecode('...')`), so casting it directly probably won't work. Instead, you'd need to create a ctor/factory on `CPStaffDetails` that takes the map and populates the fields.
