### ISSUE TITLE
Create an example for compiling and deploying a Dart-only app that uses realm

### ISSUE THREAD

**Issue by KhaledBasiony** [realm/realm-dart#1755]
### Problem

I don't know how to compile the application as an executable and distribute it.

I have a dart-only server that uses realm,
previously I was on version 1.9.0 and when trying to compile it, it was complaining about the plugin library being accessed outside of flutter (I am sure I was using realm_dart package)

now I upgraded to 3.3.0, hoping that would solve the problem, but now It depends on `.dart_tools/package_config.json`
```
Bad state: Could not find package_config.json
#0      _getPackageConfigJson (package:realm_dart/src/handles/native/init.dart:78)
#1      _openRealmLib (package:realm_dart/src/handles/native/init.dart:114)
#2      initRealm (package:realm_dart/src/handles/native/init.dart:157)
```
I don't know what I am supposed to do now

### Solution

I was hoping you could provide a section in the docs or quick start or something to show how to compile/deploy a server or a CLI application step-by-step

### How important is this improvement for you?

Dealbreaker

### Feature would mainly be used with

Atlas Device Sync

**Comment by nielsenko** [comment]
@KhaledBasiony Sorry about that - you hit a bug.

We need to find the native shared library for the realm database. One way we do that is to read and parse the `.dart_tools/package_config.json` file. If you compile your application to an exe file and copy it outside the project directory, it cannot find `package_config.json`. Obviously this should not fail the process (hence the bug), instead we should try to load the lib from elsewhere.

Since the [native assets](https://github.com/dart-lang/sdk/issues/50565) feature is not stable (yet), you will be required to manually bundle the shared lib with your application.
Unlike flutter, we cannot hook into the build process for pure dart.

**Comment by KhaledBasiony** [comment]
@nielsenko 
Thanks for the reply, I worked around it for now, by providing the shared library file and a dummy `.dart_tools/package_config.json` with the release (which is obviously not ideal, but meh)

this is necessary because `_openRealmLib` calls `_getPackageConfigJson` __Before__ asking OS to provide the shared library file, so even if the shared library exists in PATH, `.dart_tools/package_config.json` must still be there too.
