### ISSUE TITLE
Handshake error in client

### ISSUE THREAD

**Issue by sylvbravo** [realm/realm-dart#1807]
### What happened?

A bug happened! after creating a new project and adding realm as a package it throws error

### Repro steps

flutter pub add realm

dart run realm install

### Version

Flutter 3.24.4

### What Atlas Services are you using?

-- select --

### What type of application is this?

Flutter Application

### Client OS and version

realm: ^20.0.0

### Stacktrace of the exception/crash you're getting

```shell
dart run realm install
Building package executable... (9.9s)
Built realm:realm.

HostedDependency: ^20.0.0
Directory: 'C:\Users\iketoke\AppData\Local\Pub\Cache\hosted\pub.dev\realm-20.0.0\windows\binary\windows'
Downloading Realm binaries for 20.0.0 to C:\Users\IKETOKE~1\AppData\Local\Temp\realm-binary-a74a4a8\windows.tar.gz
Unhandled exception:
HandshakeException: Handshake error in client (OS Error: 
        CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../third_party/boringssl/src/ssl/handshake.cc:393))
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99:46)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:143:25)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:920:54)
#3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1049:19)
<asynchronous suspension>
```

**Comment by Bohemiaking** [comment]
same issue

**Comment by dangchinh171** [comment]
same issue.

**Comment by tdhoa** [comment]
same issue.

**Comment by quanggiau** [comment]
same issue.

**Comment by Ghelwig** [comment]
same issue.

**Comment by nirinchev** [comment]
This looks like a proxy issue or something that's preventing the SSL connection from going through from your developer machine to AWS. Not sure there's anything we can do about it - you can try downloading the packages manually and then placing them in the correct folder: https://static.realm.io/downloads/dart/20.0.0/windows.tar.gz.

**Comment by Ghelwig** [comment]
This could most likely be fixed by adding a default cert wit the HTTP package inside install_command.dart. 

https://stackoverflow.com/questions/54285172/how-to-solve-flutter-certificate-verify-failed-error-while-performing-a-post-req

If anyone is interested, this is a quick and dirty script that I wrote to install the DLL to the correct path. You would have to change the endpoint based on the realm version you are using. A few notes, the binary path does not exist after the package is grabbed so you have to make the last binary\windows path, hence mkdir. there is also a txt file in this path that needs to have the correct version in it, and writing directly to realm_version.txt did not work for me since the code threw an encoding error, so I make a separate text file and use set content to encode it to utf8 first. 

#!/bin/bash
          mkdir $env:LOCALAPPDATA\Pub\Cache\hosted\pub.dev\realm-1.2.0\windows\binary\windows

          echo -n  "1.2.0">  $env:LOCALAPPDATA\Pub\Cache\hosted\pub.dev\realm-1.2.0\windows\binary\windows\realm_version_raw.txt       

          Get-Content $env:LOCALAPPDATA\Pub\Cache\hosted\pub.dev\realm-1.2.0\windows\binary\windows\realm_version_raw.txt | Set-Content -Encoding utf8 $env:LOCALAPPDATA\Pub\Cache\hosted\pub.dev\realm-1.2.0\windows\binary\windows\realm_version.txt   -NoNewline

          curl -o $env:LOCALAPPDATA\Pub\Cache\hosted\pub.dev\realm-1.2.0\windows\binary\windows/windows.tar.gz https://static.realm.io/downloads/dart/1.2.0/windows.tar.gz  | tar -xvzf $env:LOCALAPPDATA\Pub\Cache\hosted\pub.dev\realm-1.2.0\windows\binary\windows\windows.tar.gz -C $env:LOCALAPPDATA\Pub\Cache\hosted\pub.dev\realm-1.2.0\windows\binary\windows
