### ISSUE TITLE
Contribution for Cloud Sync

### ISSUE THREAD

**Issue by dikatok** [realm/realm-dart#464]
Hi, is cloud sync support in the current work? 
Is it open for contribution?
I would like to help if it is possible since I need it for the offline capability of my app.

Thanks

**Comment by nirinchev** [comment]
Hey, really appreciate the enthusiasm! We're actively working on adding sync support and hope to have some of the core functionality ready in the near future. Out of curiosity, are you looking to add sync capabilities to an existing app or a new one? And are you interested in the new flexible sync mode or the stable partition sync?

**Comment by dikatok** [comment]
Do you have any timeline as to when the basic functionality will be ready? 
I am adding offline capabilities to an existing app, the current requirement is just to make the data available to read during network unavailability, so I am considering Realm since it is one of the most prominent solutions available or making my own in which the server will create a data bundle every now and then and the client will update its local store based on the data bundle. 
Of course, I would like to use the out-of-the-box solution if possible.

**Comment by dikatok** [comment]
As for the sync mode, I think stable partition is enough for me.

**Comment by markbreuss** [comment]
Hi @nirinchev,

thanks for the update!
We are a company which is looking to migrate to MongoDB from google firestore.
For this to be possible we need to access Atlas Hosted Mongodb services through the realm package.

Of course we understand that you cannot commit to a specific date at the moment.
However a rough estimate of you planned timeline would help us a long way to do our internal planning.

Thanks in advance!
Mark (email: mark.breuss@markone.at)

**Comment by ianpward** [comment]
We are working on it now and hope to have something this summer

**Comment by markbreuss** [comment]
Thanks for the response, this helps a lot!

**Comment by markbreuss** [comment]
Thanks a lot for the update!

**Comment by hmbenhaim** [comment]
> Web as a platform is not supported by the Realm database, so that will need to land first. It's a major undertaking and we're currently evaluating its feasibility, so it's most definitely not coming to dart in the near term.

Hi I understand that you working on sync with atlas and there is no web support for realm so it will not come to dart,
basically I saw that realm have web sdk (https://www.mongodb.com/docs/realm/web/) not for offline use but only to connect to atlas cloud. I'm wondering if this will be possible after you made the abillty of cloud sync to this as well.
we using mongodb atlas and I think it will be amazing to have this as well

Thank you

**Comment by nielsenko** [comment]
@hmbenhaim If I understand you correctly.. No, there are currently no plan of having a regular dart driver for MongoDB.  The [MongoDB Atlas Data API](https://www.mongodb.com/docs/atlas/api/data-api/) received [GA status on June 7th](https://www.mongodb.com/blog/post/atlas-data-api-generally-available-connectionless-data-access-over-https). You could perhaps use that?  Otherwise there is also the community driven [mongo_dart](https://pub.dev/packages/mongo_dart) package, not that I have any experience with it.

However, the Flutter / Dart SDK will eventually support the same functionality as the other SDKs, including the ability to call [Atlas App Services functions](https://www.mongodb.com/docs/atlas/app-services/functions/#std-label-functions) and use the online [Query API](https://www.mongodb.com/docs/manual/tutorial/query-documents/).

**Comment by desistefanova** [comment]
We already have opened issue about [Web support ](https://github.com/realm/realm-dart/issues/26). You can follow it.

**Comment by hmbenhaim** [comment]
Thank you for your comments!

**Comment by dotjon0** [comment]
Flutter Web support (https://github.com/realm/realm-dart/issues/26) would be amazing in Flutter Realm - this would certainly accelerate Flutter Web apps to market faster (& use Realm Sync more!)... Fantastic suggestion.
