### ISSUE TITLE
Add encryptionKey param to realm configuration

### ISSUE THREAD

**Issue by ahalunetsvisionable** [realm/realm-dart#677]
First of all, thank you for your work!
Please add database protection by encryptionKey as on native SDKs.
Medical applications require database protection by encryption.
Currently, direct competitors such as Isar and ObjectBox do not have database encryption. Adding such an opportunity will make your decision a more attractive solution among others.

**Comment by nirinchev** [comment]
Hey @ahalunetsvisionable, thank you for your interest in Realm. We have encryption high on our TODO list, but no timeframe that we can share yet. Since we already have an issue tracking encryption support, I'll close this one and you can subscribe to https://github.com/realm/realm-dart/issues/88 for updates.
