### ISSUE TITLE
How to sign in with google?

### ISSUE THREAD

**Issue by LeonManolo** [realm/realm-dart#718]
Is there a recommended way to sign in with google while using mongodb realm?
The only thing I found about it is this:
<img width="844" alt="Screenshot 2022-07-15 at 22 52 20" src="https://user-images.githubusercontent.com/87019114/179309011-f35fd3c4-2341-4953-8f1e-0cd43ba9f03b.png">
But how does this connection between mongodb and google work, do I have to change something here too?
<img width="950" alt="Screenshot 2022-07-15 at 22 53 44" src="https://user-images.githubusercontent.com/87019114/179309314-0840c267-e051-4187-b3cf-e982986494a5.png">

**Comment by blagoev** [comment]
Hi, 
We don't support Google authentication yet but this is on the top of our list of features for the next releases, so stay tuned.

**Comment by nielsenko** [comment]
See issue #396 (and PR #740)

**Comment by LeonManolo** [comment]
Awesome, how can I test it?
I tried it this way:

  realm_dart:
    git:
      url: https://github.com/realm/realm-dart.git
      ref: kn/auth-providers-no-tests

**Comment by nielsenko** [comment]
There are a few problems with the above. 

During development before releasing to pub.dev we use path dep on _realm_common_. When you use a git dep, you hit https://github.com/flutter/flutter/issues/47324.

Secondly, when running `dart run realm_dart install` to install the native libs you may not get the right one, since we have not rolled a proper release.

However, we will be releasing soon, and I suspect these changes will be included.

**Comment by nielsenko** [comment]
Resolved in [0.3.2+beta](https://pub.dev/packages/realm/versions/0.3.2+beta)
