### ISSUE TITLE
Sync Data to my own private server

### ISSUE THREAD

**Issue by aurthurm** [realm/realm-dart#719]
Is there a way to sync data to my own private server. Some institutions only want to store their data in their own hosted servers. Is there  a way to intercept atlas sync and redirect it to our own private servers

Thank you

**Comment by blagoev** [comment]
Hi, 
This is not supported.

**Comment by awh6al** [comment]
@blagoev Is it planned in near future?

**Comment by blagoev** [comment]
We don't have immediate plans for this

**Comment by jimisola** [comment]
Would also like to use Realm with own server(s). I understand that this was supported before MongoDB bought it. Not everyone is allowed to use cloud for storage.

**Comment by nirinchev** [comment]
We appreciate your feedback but as @blagoev said, we don't have immediate plans to support self-hosted deployments. Since this is a feature request much broader than the Realm Dart/Flutter SDK, I would suggest that you request it on our [feedback page](https://feedback.mongodb.com/forums/945334-atlas-app-services) which our product team continuously monitors and takes into consideration when prioritizing future work.
