### ISSUE TITLE
deleteAll with Flexible Sync

### ISSUE THREAD

**Issue by elhe26** [realm/realm-dart#736]
Hi @nielsenko,

How does `realm.deleteAll()` work when used with flexible sync? Will this delete all records (locally and atlas)?

Edit:

What would be the way to delete all records locally without affecting atlas? This is necessary when a user logs out.

**Comment by nielsenko** [comment]
Deletes are propagated to Atlas as well. But each object is deleted separately. This means that if the server has 3 objects, of which only 2 are present on the client when it calls `realm.deleteAll<X>()` then only those 2 objects will be deleted.

Why do you need to delete on logout?

**Comment by nirinchev** [comment]
Rather than delete the objects in the database, it's better to delete the database itself. You can use `Realm.deleteRealm` to achieve that.

**Comment by elhe26** [comment]
When a user logs out, there's a `db_shop.realm` file lingering in the phone. Is there a way to delete this file using the library?

**Comment by elhe26** [comment]
> the user-centric data is hanging of a user object, so that it is not a problem that the data from the previous user remains.

@nielsenko what do you mean by this?

**Comment by nielsenko** [comment]
Sorry for being unclear. Let me try to elaborate..

Say your app is a logistics app, with drivers handling goods. Associate a driver object with each user, and sync only the driver object for the currently logged in user. The driver object should hold all the driver private data, or references to the same.

If at any time there are two or more driver objects in the realm, because sync has not caught up yet, then it doesn't really matter because you only ever show data from the driver object associated with the currently logged in user (or objects reachable from the same).

This allows you to share some objects across logins. In my example, routes, stops, etc. that can be safely shared, but keep other stuff "private", fx. time tracking, etc.

**Comment by elhe26** [comment]
Oh, ok. Basically, filter data by user. Thanks.

**Comment by nielsenko** [comment]
When subscriptions are updated, and some locally available data suddenly no longer belongs on the device, they are removed (locally - not from Atlas).

This process is fairly fast, and you could just await synchronisation after login to prevent stale data from the previous user from appearing in your queries, but I think it is better to structure your code, so that it doesn't depend on this.

I like to think of subscriptions as the data you wish for, as opposed to the data you have. Sync will work hard to align the two, but you should not depend on it. I find that this mental model keeps you out of trouble better.

NB: The realm file won't actually shrink when objects are deleted, but the space will be re-used.

**Comment by elhe26** [comment]
> When subscriptions are updated, and some locally available data suddenly no longer belongs on the device, they are removed (locally - not from Atlas).
> 
> This process is fairly fast, and you could just await synchronisation after login to prevent stale data from the previous user from appearing in your queries, but I think it is better to structure your code, so that it doesn't depend on this.
> 
> I like to think of subscriptions as the data you wish for, as opposed to the data you have. Sync will work hard to align the two, but you should not depend on it. I find that this mental model keeps you out of trouble better.
> 
> NB: The realm file won't actually shrink when objects are deleted, but the space will be re-used.

This is excellent. Thanks! Closing this issue.
