### ISSUE TITLE
Roadmap or release schedule ?

### ISSUE THREAD

**Issue by xeno-sama** [realm/realm-dart#848]
Just wonder how can we get news about what's going with project ?

what's changing / adding / improving  .. ... et cetera

**Comment by nielsenko** [comment]
> Just wonder how can we get news about what's going with project ?
> 
> what's changing / adding / improving .. ... et cetera

We include that info in the `CHANGELOG.md`. 

By company policy we don't share roadmaps publicly. If you look at our github issues you should get some sense of what is outstanding.

Since we are releasing `realm` and `realm_dart` version **0.3.2+beta** today, I guess I can say that much.

**Comment by nielsenko** [comment]
And now they are live 😄 
- [realm 0.3.2+beta](https://pub.dev/packages/realm/versions/0.3.2+beta)
- [realm_dart 0.3.2+beta](https://pub.dev/packages/realm_dart/versions/0.3.2+beta )

**Comment by xeno-sama** [comment]
> And now they are live 😄
> 
> * [realm 0.3.2+beta](https://pub.dev/packages/realm/versions/0.3.2+beta)
> * [realm_dart 0.3.2+beta](https://pub.dev/packages/realm_dart/versions/0.3.2+beta)

thx for reply

pretty much of improvements and useful additions .. may be deserve naming as 0.4 beta :)

**Comment by nielsenko** [comment]
Since there are no breaking changes on our part and we are still pre-1.0 we didn't update the minor number.

It has later come to our attention that -  since we use `Finalizable` (from Dart 2.17) - it is possible to hit this issue: https://github.com/dart-lang/sdk/issues/49075, that was fixed in Dart version 2.17.5 (latest stable is 2.17.6). So if you are using plain dart, and not compiling, you may need to upgrade.
