### ISSUE TITLE
Production usage?

### ISSUE THREAD

**Issue by SApolinario** [realm/realm-dart#862]
Are still missing many bits and data types that would prevent this package from being used in production?  Would you recommend against using the latest?

Thanks

Samuel

**Comment by nirinchev** [comment]
Hey, so as with any beta software, using it in production has its risks, so we it's your call on whether the benefits justify the risk. That being said, we feel pretty good about the stability of existing functionality. As we're based on a database that is heavily used in production, we expect the functionality that is implemented to be robust and stable enough for production usage.

The reason why we're designating the project as beta is because there's a fair amount of features supported by other Realm SDKs that we want to support. It also gives us a little bit more flexibility when it comes to breaking changes. We don't expect any major breaking changes before we go GA, but we may change some things based on user feedback.

**Comment by SApolinario** [comment]
Thanks for the reply.  Definetely going to have a look at implementing the package.  Not sure if I'm going live with it yet or not.  Thanks again!
